# A scrape configuration scraping a Node Exporter and the Prometheus server
# itself.
global:
  scrape_interval: 1s
  scrape_timeout: 1s
  evaluation_interval: 1s
scrape_configs:
- job_name: 'smf-service'
  static_configs:
  - targets: ['docker.for.mac.localhost:10084']
- job_name: 'smf-nodemgr'
  static_configs:
  - targets: ['docker.for.mac.localhost:10082']
